#!/usr/bin/env python3
from multiprocessing import Pool
from eccodes import *
import h5py
import numpy as np
from datetime import datetime 
import glob, argparse, os
repoPath = os.path.dirname( os.path.realpath(__file__) ) 
"""
To Do list on this thing:
1. Put in something for QC values with stuff from Netcdf.
"""

def getDatetimeFromUnix( d ):
    return datetime.utcfromtimestamp( d) 

def go ( ncfile  ): 
    outputFilename = ncfile.replace('.nc','.bufr')   
    inputData = readNc( ncfile )
    #idxWave are the indices for the 431 subset WITH guardbands, idxBufr are the index values typically associated with bufr files (the 2211 we're used to).
    idxWave, idxBuf = readSubset()

    # with BUFR we need some sort of grouping in time. For each increasing minute select a chunk of the data
    unixTimeSeconds = inputData['Time']
    previousTime = datetime.utcfromtimestamp( unixTimeSeconds[0] )
    groups = []
    istore = 0  
    for i,t in enumerate( unixTimeSeconds ):
        currentTime = getDatetimeFromUnix( t ) 
        if (currentTime.minute != previousTime.minute):
            groups.append([istore,i+1])
            istore = i
        previousTime = currentTime
    # cap off anything that didn't get capped off in the loop.
    # if the minute never ended, then just put a group for the entire length of file.
    if(len(groups)>0): 
        if(groups[-1][1] != i):
            groups.append([istore,i+1])
    else:
        groups.append([0,i+1])

    # for each group make a bufr message.
    # blank out the outputfile in case we're running again. (bufr_encode uses 'ba' or append).
    f = open(outputFilename,'wb')
    f.close()

    # output in bufr with each "group" as a new message.
    for g in groups:
        bufr_encode(inputData, outputFilename, idxWave, idxBuf, g)
  
def readNc( ncfile ):
    """
    Read the cloud cleared radiance NETCDF file.
    """
    h5 = h5py.File( ncfile, 'r')
    fields = [ 'Scan_Line', 'Time', 'Number_of_Rspares', 'Solar_Zenith', 'CrIS_FORs',\
               'CrIS_Frequencies',  'CrIS_Latitude', 'Quality_Flag', 'CrIS_Radiances',\
               'CrIS_Longitude',  'Satellite_Height', 'CrIS_View_Angle', 'quality_information']
    d = {}
    # go through the fields we want, and make them into numpy arrays.
    for f in fields:
        d[f] = np.asarray(h5[f])

    # convert time from unix time in milliseconds, to seconds.
    d['Time'] = d['Time']/1000.0 

    return d

def scanAngleToZenithAngle( scanAngle, satelliteHeight, latitude, altitudeSurface = 0.0 ):
    """
    convert scan angle (in CRTM notation)/ View Angle ( in CrIS CCR notation ) to Satellite Zenith Angle
    scanAngle : units degrees
    satelliteHeight: units km
    altitudeSurface: units km (Well, as long as distance units are consistent we don't really care, but in this script, that is what they are). 
    """
    Re = 6378.16
    Rp = 6356.77
    beta = 0.9966464 #could be Rp/Re if you want. 
    Rearth =  Re/np.sqrt( np.sin( np.deg2rad(latitude) )**2/beta**2 + np.cos( np.deg2rad(latitude) )**2)
    Rs = satelliteHeight + Rearth
    Ra = Rearth + altitudeSurface
    # remove +/- scan angle, because the GSI will try to do it's own thing with -/+
    # it assumes that the data will not have a sign attached to it yet. 
    scanAngle = np.abs(scanAngle) 
    return np.rad2deg( np.arcsin( (Rs/Ra) * np.sin( np.deg2rad( scanAngle ) ) ) )  

def readSubset ():
    """
    read subset information from a file that I generated when I started that has the subsets, along with 
    the index based upon the full fsr (including guard bands) that NUCAPS uses. 
    """

    h5 = h5py.File( os.path.join(repoPath,'cris-fsr_wavenumbers.h5') ,'r')
    idxNucaps = np.asarray(h5['idxBufrSubsetInNucaps']) - 1
    idxBuf = np.asarray(h5['idxBufrSubset'])

    return idxNucaps,idxBuf

def bufr_encode(inputData, outputFilename, idxWave, idxBuf, idxTime ):
    """
    Hacked generated file from bufr_dump so we can encode our own fun data.
    """
    ibufr = codes_bufr_new_from_samples('BUFR4')
    ivalues = (12 ,)
    codes_set_array(ibufr, 'inputDelayedDescriptorReplicationFactor', ivalues)
    ivalues = (431 ,)
    codes_set_array(ibufr, 'inputExtendedDelayedDescriptorReplicationFactor', ivalues)
    codes_set(ibufr, 'edition', 4)
    codes_set(ibufr, 'masterTableNumber', 0)
    codes_set(ibufr, 'bufrHeaderCentre', 160)
    codes_set(ibufr, 'bufrHeaderSubCentre', 0)
    codes_set(ibufr, 'updateSequenceNumber', 0)
    codes_set(ibufr, 'dataCategory', 21)
    codes_set(ibufr, 'internationalDataSubCategory', 5)
    codes_set(ibufr, 'dataSubCategory', 206)
    codes_set(ibufr, 'masterTablesVersionNumber', 16)
    codes_set(ibufr, 'localTablesVersionNumber', 0)
    codes_set(ibufr, 'typicalYear', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).year)
    codes_set(ibufr, 'typicalMonth', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).month)
    codes_set(ibufr, 'typicalDay',  getDatetimeFromUnix(inputData['Time'][idxTime[0]]).day)
    codes_set(ibufr, 'typicalHour', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).hour)
    codes_set(ibufr, 'typicalMinute', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).minute)
    codes_set(ibufr, 'typicalSecond', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).second)
    codes_set(ibufr, 'numberOfSubsets', inputData['Time'][ idxTime[0]:idxTime[1] ].shape[0] )
    codes_set(ibufr, 'observedData', 1)
    codes_set(ibufr, 'compressedData', 1)
    ivalues = (
        1007, 1033, 2019, 2020, 301011, 
        301012, 207003, 4006, 207000, 304030, 
        301021, 7024, 5021, 7025, 5022, 
        8075, 201133, 5041, 201000, 5045, 
        5043, 5040, 10001, 201129, 7002, 
        201000, 202127, 201125, 21166, 201000, 
        202000, 8012, 20010, 20014, 2165, 
        33075, 107003, 8076, 6029, 6029, 
        25140, 25141, 33076, 33077, 8076, 
        33078, 33003, 104000, 31002, 201134, 
        5042, 201000, 14044, 2141, 8076, 
        104000, 31001, 201134, 5042, 201000, 
        14044, 8076, 2019, 109007, 5060, 
        5061, 25085, 105016, 5042, 8023, 
        14043, 8023, 14043,)

    # Create the structure of the data section
    codes_set_array(ibufr, 'unexpandedDescriptors', ivalues)

    codes_set(ibufr, 'satelliteIdentifier', 225)
    codes_set(ibufr, 'centre', 160)
    codes_set(ibufr, '#1#satelliteInstruments', 620)
    codes_set(ibufr, 'satelliteClassification', 3)

 

    codes_set(ibufr, 'year', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).year) 
    codes_set(ibufr, 'month', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).month)
    codes_set(ibufr, 'day', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).day)
    codes_set(ibufr, 'hour', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).hour)
    codes_set(ibufr, 'minute', getDatetimeFromUnix(inputData['Time'][idxTime[0]]).minute)

    rvalues = []
    for t in inputData['Time'][idxTime[0]:idxTime[1]]:
        rvalues.append( getDatetimeFromUnix(t).second + getDatetimeFromUnix(t).microsecond/1e6)   
    codes_set_array(ibufr, 'second', rvalues)
    codes_set(ibufr, 'DistanceFromEarthCentreInDirectionOf0DegreesLongitude', CODES_MISSING_DOUBLE)
    codes_set(ibufr, 'DistanceFromEarthCentreInDirection90DegreesEast', CODES_MISSING_DOUBLE)
    codes_set(ibufr, 'DistanceFromEarthCentreInDirectionOfNorthPole', CODES_MISSING_DOUBLE)

    codes_set_array(ibufr, 'latitude',inputData['CrIS_Latitude'][idxTime[0]:idxTime[1]].tolist())
    codes_set_array(ibufr, 'longitude', inputData['CrIS_Longitude'][idxTime[0]:idxTime[1]].tolist())

    #calculate satellite zenith Angle.
    satZA = scanAngleToZenithAngle( inputData['CrIS_View_Angle'][idxTime[0]:idxTime[1]], inputData['Satellite_Height'][idxTime[0]:idxTime[1]], inputData['CrIS_Latitude'][idxTime[0]:idxTime[1]] ) 

    codes_set_array(ibufr, 'satelliteZenithAngle', satZA.tolist())
    codes_set(ibufr, 'bearingOrAzimuth', CODES_MISSING_DOUBLE)
    codes_set_array(ibufr, 'solarZenithAngle',inputData['Solar_Zenith'][idxTime[0]:idxTime[1]].tolist() )
    codes_set(ibufr, 'solarAzimuth', CODES_MISSING_DOUBLE)
    codes_set(ibufr, 'orbitQualifier', 0)
    codes_set_array(ibufr, 'scanLineNumber', inputData['Scan_Line'][idxTime[0]:idxTime[1]].tolist())
    codes_set_array(ibufr, 'fieldOfRegardNumber', inputData['CrIS_FORs'][idxTime[0]:idxTime[1]].tolist())

    #faking field of view numbers
    fives = 5*np.ones( len(inputData['CrIS_FORs'][idxTime[0]:idxTime[1]].tolist()) )
    codes_set_array(ibufr, 'fieldOfViewNumber', fives.astype('int').tolist()  )
    codes_set(ibufr, 'orbitNumber', 36217)
    codes_set(ibufr, 'heightOfLandSurface', CODES_MISSING_LONG)
    codes_set_array(ibufr, 'height', inputData['Satellite_Height'][idxTime[0]:idxTime[1]].tolist())
    codes_set(ibufr, 'landFraction', CODES_MISSING_DOUBLE)
    codes_set(ibufr, 'landOrSeaQualifier', CODES_MISSING_DOUBLE)
    codes_set(ibufr, 'cloudCoverTotal', CODES_MISSING_LONG)
    codes_set(ibufr, 'heightOfTopOfCloud', CODES_MISSING_DOUBLE)
    codes_set(ibufr, 'radianceTypeFlags', 2048)
    codes_set(ibufr, 'scanLevelQualityFlags', 0)
    codes_set(ibufr, '#1#band', 2)
    codes_set(ibufr, '#1#waveNumber', 6.612500000000000000e+04)
    codes_set(ibufr, '#2#waveNumber', 1.095000000000000000e+05)
    codes_set(ibufr, '#1#startChannel', 19)
    codes_set(ibufr, '#1#endChannel', 713)
    codes_set(ibufr, '#1#calibrationQualityFlags', 0)
    codes_set(ibufr, '#1#fieldOfViewQualityFlags', CODES_MISSING_LONG)
    codes_set(ibufr, '#2#band', 3)
    codes_set(ibufr, '#3#waveNumber', 1.210000000000000000e+05)
    codes_set(ibufr, '#4#waveNumber', 1.745000000000000000e+05)
    codes_set(ibufr, '#2#startChannel', 714)
    codes_set(ibufr, '#2#endChannel', 1570)
    codes_set(ibufr, '#2#calibrationQualityFlags', 0)
    codes_set(ibufr, '#2#fieldOfViewQualityFlags', CODES_MISSING_LONG)
    codes_set(ibufr, '#3#band', 4)
    codes_set(ibufr, '#5#waveNumber', 2.165620000000000000e+05)
    codes_set(ibufr, '#6#waveNumber', 2.531880000000000000e+05)
    codes_set(ibufr, '#3#startChannel', 1596)
    codes_set(ibufr, '#3#endChannel', 2182)
    codes_set(ibufr, '#3#calibrationQualityFlags', 0)
    codes_set(ibufr, '#3#fieldOfViewQualityFlags', CODES_MISSING_LONG)
    codes_set(ibufr, '#4#band', CODES_MISSING_LONG)
    codes_set(ibufr, 'geolocationQuality', 0)
    codes_set(ibufr, 'qualityInformation', 0)

    for ch,idx in enumerate(idxWave):
        codes_set(ibufr, '#{}#channelNumber'.format(ch+1), int(idxBuf[ch]))
        codes_set_array(ibufr, '#{}#channelRadiance'.format(ch+1), (inputData['CrIS_Radiances'][idxTime[0]:idxTime[1],idx]/1000).tolist() )


    codes_set(ibufr, 'measurementType','FSR')
    codes_set(ibufr, '#5#band', 8)
    codes_set(ibufr, '#432#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#432#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#433#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#433#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#434#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#434#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#435#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#435#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#436#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#436#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#437#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#437#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#438#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#438#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#439#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#439#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#440#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#440#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#441#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#441#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#442#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#442#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#443#channelNumber', CODES_MISSING_LONG)
    codes_set(ibufr, '#443#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#6#band', CODES_MISSING_LONG)
    codes_set(ibufr, '#2#satelliteInstruments', 616)
    codes_set(ibufr, '#1#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#1#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#1#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#444#channelNumber', 1)
    codes_set(ibufr, '#1#firstOrderStatistics', 4)
    codes_set(ibufr, '#444#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#2#firstOrderStatistics', 10)
    codes_set(ibufr, '#445#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#445#channelNumber', 2)
    codes_set(ibufr, '#3#firstOrderStatistics', 4)
    codes_set(ibufr, '#446#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#4#firstOrderStatistics', 10)
    codes_set(ibufr, '#447#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#446#channelNumber', 3)
    codes_set(ibufr, '#5#firstOrderStatistics', 4)
    codes_set(ibufr, '#448#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#6#firstOrderStatistics', 10)
    codes_set(ibufr, '#449#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#447#channelNumber', 4)
    codes_set(ibufr, '#7#firstOrderStatistics', 4)
    codes_set(ibufr, '#450#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#8#firstOrderStatistics', 10)
    codes_set(ibufr, '#451#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#448#channelNumber', 5)
    codes_set(ibufr, '#9#firstOrderStatistics', 4)
    codes_set(ibufr, '#452#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#10#firstOrderStatistics', 10)
    codes_set(ibufr, '#453#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#449#channelNumber', 6)
    codes_set(ibufr, '#11#firstOrderStatistics', 4)
    codes_set(ibufr, '#454#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#12#firstOrderStatistics', 10)
    codes_set(ibufr, '#455#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#450#channelNumber', 7)
    codes_set(ibufr, '#13#firstOrderStatistics', 4)
    codes_set(ibufr, '#456#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#14#firstOrderStatistics', 10)
    codes_set(ibufr, '#457#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#451#channelNumber', 8)
    codes_set(ibufr, '#15#firstOrderStatistics', 4)
    codes_set(ibufr, '#458#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#16#firstOrderStatistics', 10)
    codes_set(ibufr, '#459#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#452#channelNumber', 9)
    codes_set(ibufr, '#17#firstOrderStatistics', 4)
    codes_set(ibufr, '#460#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#18#firstOrderStatistics', 10)
    codes_set(ibufr, '#461#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#453#channelNumber', 10)
    codes_set(ibufr, '#19#firstOrderStatistics', 4)
    codes_set(ibufr, '#462#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#20#firstOrderStatistics', 10)
    codes_set(ibufr, '#463#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#454#channelNumber', 11)
    codes_set(ibufr, '#21#firstOrderStatistics', 4)
    codes_set(ibufr, '#464#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#22#firstOrderStatistics', 10)
    codes_set(ibufr, '#465#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#455#channelNumber', 12)
    codes_set(ibufr, '#23#firstOrderStatistics', 4)
    codes_set(ibufr, '#466#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#24#firstOrderStatistics', 10)
    codes_set(ibufr, '#467#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#456#channelNumber', 13)
    codes_set(ibufr, '#25#firstOrderStatistics', 4)
    codes_set(ibufr, '#468#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#26#firstOrderStatistics', 10)
    codes_set(ibufr, '#469#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#457#channelNumber', 14)
    codes_set(ibufr, '#27#firstOrderStatistics', 4)
    codes_set(ibufr, '#470#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#28#firstOrderStatistics', 10)
    codes_set(ibufr, '#471#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#458#channelNumber', 15)
    codes_set(ibufr, '#29#firstOrderStatistics', 4)
    codes_set(ibufr, '#472#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#30#firstOrderStatistics', 10)
    codes_set(ibufr, '#473#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#459#channelNumber', 16)
    codes_set(ibufr, '#31#firstOrderStatistics', 4)
    codes_set(ibufr, '#474#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#32#firstOrderStatistics', 10)
    codes_set(ibufr, '#475#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#2#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#2#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#2#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#460#channelNumber', 1)
    codes_set(ibufr, '#33#firstOrderStatistics', 4)
    codes_set(ibufr, '#476#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#34#firstOrderStatistics', 10)
    codes_set(ibufr, '#477#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#461#channelNumber', 2)
    codes_set(ibufr, '#35#firstOrderStatistics', 4)
    codes_set(ibufr, '#478#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#36#firstOrderStatistics', 10)
    codes_set(ibufr, '#479#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#462#channelNumber', 3)
    codes_set(ibufr, '#37#firstOrderStatistics', 4)
    codes_set(ibufr, '#480#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#38#firstOrderStatistics', 10)
    codes_set(ibufr, '#481#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#463#channelNumber', 4)
    codes_set(ibufr, '#39#firstOrderStatistics', 4)
    codes_set(ibufr, '#482#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#40#firstOrderStatistics', 10)
    codes_set(ibufr, '#483#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#464#channelNumber', 5)
    codes_set(ibufr, '#41#firstOrderStatistics', 4)
    codes_set(ibufr, '#484#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#42#firstOrderStatistics', 10)
    codes_set(ibufr, '#485#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#465#channelNumber', 6)
    codes_set(ibufr, '#43#firstOrderStatistics', 4)
    codes_set(ibufr, '#486#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#44#firstOrderStatistics', 10)
    codes_set(ibufr, '#487#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#466#channelNumber', 7)
    codes_set(ibufr, '#45#firstOrderStatistics', 4)
    codes_set(ibufr, '#488#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#46#firstOrderStatistics', 10)
    codes_set(ibufr, '#489#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#467#channelNumber', 8)
    codes_set(ibufr, '#47#firstOrderStatistics', 4)
    codes_set(ibufr, '#490#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#48#firstOrderStatistics', 10)
    codes_set(ibufr, '#491#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#468#channelNumber', 9)
    codes_set(ibufr, '#49#firstOrderStatistics', 4)
    codes_set(ibufr, '#492#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#50#firstOrderStatistics', 10)
    codes_set(ibufr, '#493#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#469#channelNumber', 10)
    codes_set(ibufr, '#51#firstOrderStatistics', 4)
    codes_set(ibufr, '#494#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#52#firstOrderStatistics', 10)
    codes_set(ibufr, '#495#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#470#channelNumber', 11)
    codes_set(ibufr, '#53#firstOrderStatistics', 4)
    codes_set(ibufr, '#496#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#54#firstOrderStatistics', 10)
    codes_set(ibufr, '#497#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#471#channelNumber', 12)
    codes_set(ibufr, '#55#firstOrderStatistics', 4)
    codes_set(ibufr, '#498#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#56#firstOrderStatistics', 10)
    codes_set(ibufr, '#499#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#472#channelNumber', 13)
    codes_set(ibufr, '#57#firstOrderStatistics', 4)
    codes_set(ibufr, '#500#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#58#firstOrderStatistics', 10)
    codes_set(ibufr, '#501#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#473#channelNumber', 14)
    codes_set(ibufr, '#59#firstOrderStatistics', 4)
    codes_set(ibufr, '#502#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#60#firstOrderStatistics', 10)
    codes_set(ibufr, '#503#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#474#channelNumber', 15)
    codes_set(ibufr, '#61#firstOrderStatistics', 4)
    codes_set(ibufr, '#504#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#62#firstOrderStatistics', 10)
    codes_set(ibufr, '#505#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#475#channelNumber', 16)
    codes_set(ibufr, '#63#firstOrderStatistics', 4)
    codes_set(ibufr, '#506#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#64#firstOrderStatistics', 10)
    codes_set(ibufr, '#507#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#3#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#3#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#3#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#476#channelNumber', 1)
    codes_set(ibufr, '#65#firstOrderStatistics', 4)
    codes_set(ibufr, '#508#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#66#firstOrderStatistics', 10)
    codes_set(ibufr, '#509#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#477#channelNumber', 2)
    codes_set(ibufr, '#67#firstOrderStatistics', 4)
    codes_set(ibufr, '#510#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#68#firstOrderStatistics', 10)
    codes_set(ibufr, '#511#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#478#channelNumber', 3)
    codes_set(ibufr, '#69#firstOrderStatistics', 4)
    codes_set(ibufr, '#512#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#70#firstOrderStatistics', 10)
    codes_set(ibufr, '#513#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#479#channelNumber', 4)
    codes_set(ibufr, '#71#firstOrderStatistics', 4)
    codes_set(ibufr, '#514#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#72#firstOrderStatistics', 10)
    codes_set(ibufr, '#515#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#480#channelNumber', 5)
    codes_set(ibufr, '#73#firstOrderStatistics', 4)
    codes_set(ibufr, '#516#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#74#firstOrderStatistics', 10)
    codes_set(ibufr, '#517#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#481#channelNumber', 6)
    codes_set(ibufr, '#75#firstOrderStatistics', 4)
    codes_set(ibufr, '#518#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#76#firstOrderStatistics', 10)
    codes_set(ibufr, '#519#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#482#channelNumber', 7)
    codes_set(ibufr, '#77#firstOrderStatistics', 4)
    codes_set(ibufr, '#520#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#78#firstOrderStatistics', 10)
    codes_set(ibufr, '#521#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#483#channelNumber', 8)
    codes_set(ibufr, '#79#firstOrderStatistics', 4)
    codes_set(ibufr, '#522#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#80#firstOrderStatistics', 10)
    codes_set(ibufr, '#523#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#484#channelNumber', 9)
    codes_set(ibufr, '#81#firstOrderStatistics', 4)
    codes_set(ibufr, '#524#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#82#firstOrderStatistics', 10)
    codes_set(ibufr, '#525#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#485#channelNumber', 10)
    codes_set(ibufr, '#83#firstOrderStatistics', 4)
    codes_set(ibufr, '#526#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#84#firstOrderStatistics', 10)
    codes_set(ibufr, '#527#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#486#channelNumber', 11)
    codes_set(ibufr, '#85#firstOrderStatistics', 4)
    codes_set(ibufr, '#528#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#86#firstOrderStatistics', 10)
    codes_set(ibufr, '#529#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#487#channelNumber', 12)
    codes_set(ibufr, '#87#firstOrderStatistics', 4)
    codes_set(ibufr, '#530#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#88#firstOrderStatistics', 10)
    codes_set(ibufr, '#531#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#488#channelNumber', 13)
    codes_set(ibufr, '#89#firstOrderStatistics', 4)
    codes_set(ibufr, '#532#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#90#firstOrderStatistics', 10)
    codes_set(ibufr, '#533#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#489#channelNumber', 14)
    codes_set(ibufr, '#91#firstOrderStatistics', 4)
    codes_set(ibufr, '#534#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#92#firstOrderStatistics', 10)
    codes_set(ibufr, '#535#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#490#channelNumber', 15)
    codes_set(ibufr, '#93#firstOrderStatistics', 4)
    codes_set(ibufr, '#536#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#94#firstOrderStatistics', 10)
    codes_set(ibufr, '#537#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#491#channelNumber', 16)
    codes_set(ibufr, '#95#firstOrderStatistics', 4)
    codes_set(ibufr, '#538#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#96#firstOrderStatistics', 10)
    codes_set(ibufr, '#539#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#4#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#4#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#4#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#492#channelNumber', 1)
    codes_set(ibufr, '#97#firstOrderStatistics', 4)
    codes_set(ibufr, '#540#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#98#firstOrderStatistics', 10)
    codes_set(ibufr, '#541#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#493#channelNumber', 2)
    codes_set(ibufr, '#99#firstOrderStatistics', 4)
    codes_set(ibufr, '#542#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#100#firstOrderStatistics', 10)
    codes_set(ibufr, '#543#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#494#channelNumber', 3)
    codes_set(ibufr, '#101#firstOrderStatistics', 4)
    codes_set(ibufr, '#544#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#102#firstOrderStatistics', 10)
    codes_set(ibufr, '#545#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#495#channelNumber', 4)
    codes_set(ibufr, '#103#firstOrderStatistics', 4)
    codes_set(ibufr, '#546#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#104#firstOrderStatistics', 10)
    codes_set(ibufr, '#547#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#496#channelNumber', 5)
    codes_set(ibufr, '#105#firstOrderStatistics', 4)
    codes_set(ibufr, '#548#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#106#firstOrderStatistics', 10)
    codes_set(ibufr, '#549#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#497#channelNumber', 6)
    codes_set(ibufr, '#107#firstOrderStatistics', 4)
    codes_set(ibufr, '#550#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#108#firstOrderStatistics', 10)
    codes_set(ibufr, '#551#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#498#channelNumber', 7)
    codes_set(ibufr, '#109#firstOrderStatistics', 4)
    codes_set(ibufr, '#552#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#110#firstOrderStatistics', 10)
    codes_set(ibufr, '#553#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#499#channelNumber', 8)
    codes_set(ibufr, '#111#firstOrderStatistics', 4)
    codes_set(ibufr, '#554#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#112#firstOrderStatistics', 10)
    codes_set(ibufr, '#555#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#500#channelNumber', 9)
    codes_set(ibufr, '#113#firstOrderStatistics', 4)
    codes_set(ibufr, '#556#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#114#firstOrderStatistics', 10)
    codes_set(ibufr, '#557#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#501#channelNumber', 10)
    codes_set(ibufr, '#115#firstOrderStatistics', 4)
    codes_set(ibufr, '#558#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#116#firstOrderStatistics', 10)
    codes_set(ibufr, '#559#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#502#channelNumber', 11)
    codes_set(ibufr, '#117#firstOrderStatistics', 4)
    codes_set(ibufr, '#560#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#118#firstOrderStatistics', 10)
    codes_set(ibufr, '#561#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#503#channelNumber', 12)
    codes_set(ibufr, '#119#firstOrderStatistics', 4)
    codes_set(ibufr, '#562#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#120#firstOrderStatistics', 10)
    codes_set(ibufr, '#563#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#504#channelNumber', 13)
    codes_set(ibufr, '#121#firstOrderStatistics', 4)
    codes_set(ibufr, '#564#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#122#firstOrderStatistics', 10)
    codes_set(ibufr, '#565#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#505#channelNumber', 14)
    codes_set(ibufr, '#123#firstOrderStatistics', 4)
    codes_set(ibufr, '#566#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#124#firstOrderStatistics', 10)
    codes_set(ibufr, '#567#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#506#channelNumber', 15)
    codes_set(ibufr, '#125#firstOrderStatistics', 4)
    codes_set(ibufr, '#568#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#126#firstOrderStatistics', 10)
    codes_set(ibufr, '#569#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#507#channelNumber', 16)
    codes_set(ibufr, '#127#firstOrderStatistics', 4)
    codes_set(ibufr, '#570#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#128#firstOrderStatistics', 10)
    codes_set(ibufr, '#571#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#5#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#5#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#5#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#508#channelNumber', 1)
    codes_set(ibufr, '#129#firstOrderStatistics', 4)
    codes_set(ibufr, '#572#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#130#firstOrderStatistics', 10)
    codes_set(ibufr, '#573#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#509#channelNumber', 2)
    codes_set(ibufr, '#131#firstOrderStatistics', 4)
    codes_set(ibufr, '#574#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#132#firstOrderStatistics', 10)
    codes_set(ibufr, '#575#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#510#channelNumber', 3)
    codes_set(ibufr, '#133#firstOrderStatistics', 4)
    codes_set(ibufr, '#576#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#134#firstOrderStatistics', 10)
    codes_set(ibufr, '#577#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#511#channelNumber', 4)
    codes_set(ibufr, '#135#firstOrderStatistics', 4)
    codes_set(ibufr, '#578#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#136#firstOrderStatistics', 10)
    codes_set(ibufr, '#579#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#512#channelNumber', 5)
    codes_set(ibufr, '#137#firstOrderStatistics', 4)
    codes_set(ibufr, '#580#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#138#firstOrderStatistics', 10)
    codes_set(ibufr, '#581#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#513#channelNumber', 6)
    codes_set(ibufr, '#139#firstOrderStatistics', 4)
    codes_set(ibufr, '#582#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#140#firstOrderStatistics', 10)
    codes_set(ibufr, '#583#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#514#channelNumber', 7)
    codes_set(ibufr, '#141#firstOrderStatistics', 4)
    codes_set(ibufr, '#584#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#142#firstOrderStatistics', 10)
    codes_set(ibufr, '#585#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#515#channelNumber', 8)
    codes_set(ibufr, '#143#firstOrderStatistics', 4)
    codes_set(ibufr, '#586#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#144#firstOrderStatistics', 10)
    codes_set(ibufr, '#587#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#516#channelNumber', 9)
    codes_set(ibufr, '#145#firstOrderStatistics', 4)
    codes_set(ibufr, '#588#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#146#firstOrderStatistics', 10)
    codes_set(ibufr, '#589#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#517#channelNumber', 10)
    codes_set(ibufr, '#147#firstOrderStatistics', 4)
    codes_set(ibufr, '#590#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#148#firstOrderStatistics', 10)
    codes_set(ibufr, '#591#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#518#channelNumber', 11)
    codes_set(ibufr, '#149#firstOrderStatistics', 4)
    codes_set(ibufr, '#592#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#150#firstOrderStatistics', 10)
    codes_set(ibufr, '#593#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#519#channelNumber', 12)
    codes_set(ibufr, '#151#firstOrderStatistics', 4)
    codes_set(ibufr, '#594#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#152#firstOrderStatistics', 10)
    codes_set(ibufr, '#595#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#520#channelNumber', 13)
    codes_set(ibufr, '#153#firstOrderStatistics', 4)
    codes_set(ibufr, '#596#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#154#firstOrderStatistics', 10)
    codes_set(ibufr, '#597#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#521#channelNumber', 14)
    codes_set(ibufr, '#155#firstOrderStatistics', 4)
    codes_set(ibufr, '#598#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#156#firstOrderStatistics', 10)
    codes_set(ibufr, '#599#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#522#channelNumber', 15)
    codes_set(ibufr, '#157#firstOrderStatistics', 4)
    codes_set(ibufr, '#600#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#158#firstOrderStatistics', 10)
    codes_set(ibufr, '#601#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#523#channelNumber', 16)
    codes_set(ibufr, '#159#firstOrderStatistics', 4)
    codes_set(ibufr, '#602#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#160#firstOrderStatistics', 10)
    codes_set(ibufr, '#603#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#6#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#6#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#6#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#524#channelNumber', 1)
    codes_set(ibufr, '#161#firstOrderStatistics', 4)
    codes_set(ibufr, '#604#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#162#firstOrderStatistics', 10)
    codes_set(ibufr, '#605#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#525#channelNumber', 2)
    codes_set(ibufr, '#163#firstOrderStatistics', 4)
    codes_set(ibufr, '#606#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#164#firstOrderStatistics', 10)
    codes_set(ibufr, '#607#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#526#channelNumber', 3)
    codes_set(ibufr, '#165#firstOrderStatistics', 4)
    codes_set(ibufr, '#608#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#166#firstOrderStatistics', 10)
    codes_set(ibufr, '#609#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#527#channelNumber', 4)
    codes_set(ibufr, '#167#firstOrderStatistics', 4)
    codes_set(ibufr, '#610#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#168#firstOrderStatistics', 10)
    codes_set(ibufr, '#611#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#528#channelNumber', 5)
    codes_set(ibufr, '#169#firstOrderStatistics', 4)
    codes_set(ibufr, '#612#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#170#firstOrderStatistics', 10)
    codes_set(ibufr, '#613#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#529#channelNumber', 6)
    codes_set(ibufr, '#171#firstOrderStatistics', 4)
    codes_set(ibufr, '#614#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#172#firstOrderStatistics', 10)
    codes_set(ibufr, '#615#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#530#channelNumber', 7)
    codes_set(ibufr, '#173#firstOrderStatistics', 4)
    codes_set(ibufr, '#616#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#174#firstOrderStatistics', 10)
    codes_set(ibufr, '#617#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#531#channelNumber', 8)
    codes_set(ibufr, '#175#firstOrderStatistics', 4)
    codes_set(ibufr, '#618#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#176#firstOrderStatistics', 10)
    codes_set(ibufr, '#619#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#532#channelNumber', 9)
    codes_set(ibufr, '#177#firstOrderStatistics', 4)
    codes_set(ibufr, '#620#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#178#firstOrderStatistics', 10)
    codes_set(ibufr, '#621#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#533#channelNumber', 10)
    codes_set(ibufr, '#179#firstOrderStatistics', 4)
    codes_set(ibufr, '#622#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#180#firstOrderStatistics', 10)
    codes_set(ibufr, '#623#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#534#channelNumber', 11)
    codes_set(ibufr, '#181#firstOrderStatistics', 4)
    codes_set(ibufr, '#624#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#182#firstOrderStatistics', 10)
    codes_set(ibufr, '#625#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#535#channelNumber', 12)
    codes_set(ibufr, '#183#firstOrderStatistics', 4)
    codes_set(ibufr, '#626#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#184#firstOrderStatistics', 10)
    codes_set(ibufr, '#627#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#536#channelNumber', 13)
    codes_set(ibufr, '#185#firstOrderStatistics', 4)
    codes_set(ibufr, '#628#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#186#firstOrderStatistics', 10)
    codes_set(ibufr, '#629#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#537#channelNumber', 14)
    codes_set(ibufr, '#187#firstOrderStatistics', 4)
    codes_set(ibufr, '#630#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#188#firstOrderStatistics', 10)
    codes_set(ibufr, '#631#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#538#channelNumber', 15)
    codes_set(ibufr, '#189#firstOrderStatistics', 4)
    codes_set(ibufr, '#632#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#190#firstOrderStatistics', 10)
    codes_set(ibufr, '#633#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#539#channelNumber', 16)
    codes_set(ibufr, '#191#firstOrderStatistics', 4)
    codes_set(ibufr, '#634#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#192#firstOrderStatistics', 10)
    codes_set(ibufr, '#635#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#7#yAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#7#zAngularPositionFromCentreOfGravity', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#7#fractionOfClearPixelsInHirsFov', CODES_MISSING_LONG)
    codes_set(ibufr, '#540#channelNumber', 1)
    codes_set(ibufr, '#193#firstOrderStatistics', 4)
    codes_set(ibufr, '#636#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#194#firstOrderStatistics', 10)
    codes_set(ibufr, '#637#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#541#channelNumber', 2)
    codes_set(ibufr, '#195#firstOrderStatistics', 4)
    codes_set(ibufr, '#638#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#196#firstOrderStatistics', 10)
    codes_set(ibufr, '#639#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#542#channelNumber', 3)
    codes_set(ibufr, '#197#firstOrderStatistics', 4)
    codes_set(ibufr, '#640#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#198#firstOrderStatistics', 10)
    codes_set(ibufr, '#641#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#543#channelNumber', 4)
    codes_set(ibufr, '#199#firstOrderStatistics', 4)
    codes_set(ibufr, '#642#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#200#firstOrderStatistics', 10)
    codes_set(ibufr, '#643#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#544#channelNumber', 5)
    codes_set(ibufr, '#201#firstOrderStatistics', 4)
    codes_set(ibufr, '#644#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#202#firstOrderStatistics', 10)
    codes_set(ibufr, '#645#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#545#channelNumber', 6)
    codes_set(ibufr, '#203#firstOrderStatistics', 4)
    codes_set(ibufr, '#646#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#204#firstOrderStatistics', 10)
    codes_set(ibufr, '#647#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#546#channelNumber', 7)
    codes_set(ibufr, '#205#firstOrderStatistics', 4)
    codes_set(ibufr, '#648#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#206#firstOrderStatistics', 10)
    codes_set(ibufr, '#649#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#547#channelNumber', 8)
    codes_set(ibufr, '#207#firstOrderStatistics', 4)
    codes_set(ibufr, '#650#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#208#firstOrderStatistics', 10)
    codes_set(ibufr, '#651#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#548#channelNumber', 9)
    codes_set(ibufr, '#209#firstOrderStatistics', 4)
    codes_set(ibufr, '#652#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#210#firstOrderStatistics', 10)
    codes_set(ibufr, '#653#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#549#channelNumber', 10)
    codes_set(ibufr, '#211#firstOrderStatistics', 4)
    codes_set(ibufr, '#654#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#212#firstOrderStatistics', 10)
    codes_set(ibufr, '#655#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#550#channelNumber', 11)
    codes_set(ibufr, '#213#firstOrderStatistics', 4)
    codes_set(ibufr, '#656#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#214#firstOrderStatistics', 10)
    codes_set(ibufr, '#657#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#551#channelNumber', 12)
    codes_set(ibufr, '#215#firstOrderStatistics', 4)
    codes_set(ibufr, '#658#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#216#firstOrderStatistics', 10)
    codes_set(ibufr, '#659#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#552#channelNumber', 13)
    codes_set(ibufr, '#217#firstOrderStatistics', 4)
    codes_set(ibufr, '#660#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#218#firstOrderStatistics', 10)
    codes_set(ibufr, '#661#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#553#channelNumber', 14)
    codes_set(ibufr, '#219#firstOrderStatistics', 4)
    codes_set(ibufr, '#662#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#220#firstOrderStatistics', 10)
    codes_set(ibufr, '#663#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#554#channelNumber', 15)
    codes_set(ibufr, '#221#firstOrderStatistics', 4)
    codes_set(ibufr, '#664#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#222#firstOrderStatistics', 10)
    codes_set(ibufr, '#665#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#555#channelNumber', 16)
    codes_set(ibufr, '#223#firstOrderStatistics', 4)
    codes_set(ibufr, '#666#channelRadiance', CODES_MISSING_DOUBLE)
    codes_set(ibufr, '#224#firstOrderStatistics', 10)
    codes_set(ibufr, '#667#channelRadiance', CODES_MISSING_DOUBLE)

    # Encode the keys back in the data section
    codes_set(ibufr, 'pack', 1)

    outfile = open(outputFilename, 'ab')
    codes_write(ibufr, outfile)
    codes_release(ibufr)

if __name__ =="__main__":
    parser = argparse.ArgumentParser( description = "Convert CCR Netcdf to bufr.")
    parser.add_argument('--inpath', help = 'input directory', required = True, dest = 'path')
    parser.add_argument('--threads', help = 'number of threads', required = True, dest = 'nthreads')

    a = parser.parse_args()
    files = glob.glob( os.path.join(a.path,'*.nc') )
    p = Pool( int( a.nthreads ) )
    # pass ichans in as non-iterable via partial.
    print("Initialized Pool: {} threads.".format(a.nthreads))
    print( "Processing {} files.".format( len(files) ) )
    returns = p.map( go, files) 
    print('Done!')
